<?php
// alowed services list
$config['allowed_services'] = array(
    'region.regionSiteList',//地区分站列表
    'region.getRegion',//获取地区信息
    'region.getSendTime',//获取配送时间
    'region.getPay',//获取支付方式
    'region.getChargePay',//获取充值支付方式
    'marketing.banner',//首页广告图
    'marketing.chargeRules',
    'marketing.baseSetting',
    'marketing.indexProduct',
    'product.category',//分类商品
    'product.search',//商品搜索
    'product.searchKey',//热门搜索关键字
    'product.productInfo',//商品详情
    'product.productDetail',//商品描述
    'product.getCatList',//商品分类
    'product.pageListProducts',//商品专题页面
    'product.commentsRate',//商品评论星级
    'product.comments',//商品评论
    'product.recommend',//商品推荐
    'product.sendInfo',//商品配送信息
    'user.recommend',//商品推荐
    'user.notice',//会员中心提醒
    'order.invoiceTitleList',//发票抬头列表
    'user.signin',
    'user.oAuthSignin',
    'user.sendPhoneTicket',
    'user.checkRegister',
    'user.register',
    'user.register_V102',
    'user.signout',
    'user.password',
    'user.sendVerCode',
    'user.forgetPasswd',
    'user.userInfo',
    'user.userCouponList',
    'user.userGifts',
    'user.receiveUserGifts',
    'user.receiveUserGifts_V110',
    'user.receiveUserGiftCard',
    'user.giftCardCharge',
    'user.userCharge',
    'user.shareReward',
    'user.bindMobile',
	'user.checkMobileAuth',
	'user.getMsgSetting',
	'user.updateMsgSetting',
    'user.userScore',
    'user.userTransaction',
    'user.userShareActive',
    'user.usershare1117',
    'user.wegame',
    'user.shake_shake',
    'user.shake_exchange',
    'user.shake_history',
    'user.upUserInfo',
    'user.privilegeList',
    'user.privilegeList_V2',
    'user.giftsGet',
    'user.gcouponGet',
	'user.getInvoice',
    'user.welfare',
    'user.wegame',
    'user.getLoginError',
    'user.setLoginError',
    'user.levelLog',
    'user.checkRedIndicator',
    'user.cancelRedIndicator',
    'user.updateBasic',
	'user.sendEmail',
    'userinvite.getJF',
    'userinvite.getInvite',
    'userinvite.getGift',
    'userinvite.checkIfInvite',
    'userinvite.getInviteById',
    'userinvite.updateFinishOrder',
    'userinvite.sendInviteGift',
    'userinvite.countAdd',

    'order.finish',
    'order.orderInit',
    'order.getAddrList',
    'order.addAddr',
    'order.updateAddr',
    'order.deleteAddr',
    'order.choseAddr',
    'order.getAddr',
    'order.choseSendtime',
    'order.chosePayment',
    'order.usejf',
    'order.cancelUsejf',
    'order.useCard',
    'order.cancelUseCard',
    'order.postFree',
    'order.createOrder',
    'order.orderList',
    'order.orderInfo',
    'order.orderCancel',
    'order.orderPayed',
    'order.orderPayed_V130',
    'order.checkUserMoney',
    'order.confirmReceive',
    'order.useInvoice',
	'order.useTradeInvoice',
    'order.cancelInvoice',
    'order.invoiceInfo',
    'order.appealList',
    'order.doComment',
    'order.doAppeal',
    'order.logisticTrace',
    'order.commentList',
    'product.mark',
    'product.cancelMark',
    'product.markStatus',
    'product.markList',
    //'product.appeal',
    'product.enterpriseProducts',
    'product.markedProducts',
    'product.productList',
    'product.getProductClass',
    // 'comment.doComment',
    // 'comment.getCommentList',
    // 'sharecomment.getCommentList',
    // 'sharecomment.doComment',
    // 'comment.getCommentList_V2',
    // 'comment.doComment_V2',
    'fruit.getTopicList',
    'fruit.getDetailTopic',
    'fruit.delComment',
    'fruit.delArticle',
    'fruit.checkInvate',
    'fruit.doArticle',
    'fruit.doUserface',
    'fruit.doComment',
    'fruit.doWorth',
    'fruit.undoWorth',
    'fruit.setWorth',
    'fruit.getArticleList',
    'fruit.getDetailArticle',
    'fruit.getArtCommentList',
    'fruit.getFruitUserInfo',
    'fruit.getCommentArticleList',
    'fruit.getUserArticleList',
    'fruit.getCommentArticleList',
    'fruit.getWorthArticleList',
    'fruit.listNotify',
    'fruit.upNotify',
    'fruit.getMaxArticleList',
    'bake.getSectionList',
    'bake.getArticleList',
    'bake.getDetailArticle',
    'bake.setWorth',
    'bake.setCollect',
    'bake.doComment',
    'bake.getArtCommentList',
    'bake.getSearchTagList',
    'bake.delComment',
    'snscenter.getUserInfo',
    'snscenter.getUserArticleList',
    'snscenter.getMaxCommentArticleList',
    'snscenter.getCollectArticleList',
    'snscenter.listNotify',
    'snscenter.upNotify',
    'user.bindAccount',
    'foretaste.getCurList',
    'foretaste.getDetail',
    'foretaste.checkApply',
    'foretaste.doApply',
    'foretaste.ownerApply',
    'foretaste.getCommentList',
    'foretaste.doComment',
    'foretaste.reportInfo',
    'foretaste.getInfoByPro', // 获取商品的试吃评论数
    'cardchange.checkExchange',
    'cardchange.createOrder',
    'cart.add',
    'cart.remove',
    'cart.update',
    'cart.empty',
    'cart.get',
	'cart.newget',
    'cart.selpmt',
    'cart.clear',
    'cart.count',
    'o2o.regionlist',
    'o2o.nearbyBszone',
    'o2o.lastAddress',
    'o2o.addresslist',
    'o2o.storeproducts',
    'o2o.total',
    'o2o.orderInit',
    'o2o.createOrder',
    'o2o.nearbystore',
    'o2o.commonstores',
    'o2o.citystores',
    'o2o.exchgcoupon',
    'o2o.nearbyBuilding',
    'o2o.getPay',
    'o2o.searchBuilding',
    'o2o.getStroeInfo',
    'o2o.nearbyBuilding_new',
    'o2o.getStoreList',
    //'o2o.getStoreGoodsInfo',
    'o2o.getStoreOtherGoods',
    'o2o.getHomePageInfo',
    'o2o.o2oProductList',
    'o2o.productInfo',
    'o2o.orderInit_new',
    'o2o.createOrder_new',
    'o2o.pageListProducts',
    'o2o.getGoodsDetailBanner',
    'kjt.checkStore',
    'kjt.createOrder',
    'kjt.orderInit',
    'kjt.productInfo',
    'kjt.getKjtProducts',

    'group.checkStore',
    'group.createOrder',
    'group.orderInit',
    'group.productInfo',
    'group.canBuy',
    'group.getSoutNum',
    'group.getGroupInfo',
    'group.beforeOrder',

    'order.pushoms',
    'recharge.pushoms',
    'open.getMobile',
//    'open.getOrangeCard',
    'o2o.orderList',
    'crm.getUserInfo',
    'crm.getMessage',
    'crm.delMessage',
    'crm.tradeList',
    'crm.cardOrder',
    'crm.userJf',
    'crm.tiHuoQuan',
    'crm.chargeCard',
    'crm.unSent',
    'crm.orderList',
    'crm.saveCard',
    'crm.operateJf',
    'crm.getUserInfo',
    'crm.orderList',
    'crm.saveCard',
    'crm.orderDetail',
    'crm.getMobile',
    'crm.resetProUnused',
    'crm.receiveFeedback',
    'crm.freezeUser',
    'wx.bind',
    'wx.unbind',
    'wx.set_user_info',
    'wx.getUserInfo',
    'wx.getShipingInfo',
    'wx.getCards',
    'wx.getUserGifts',
    'wx.getScore',
    'wx.checkLogin',
    'o2ocart.add',
    'o2ocart.remove',
    'o2ocart.update',
    'o2ocart.get',
    'o2ocart.selpmt',
    'o2ocart.clear',
    'o2ocart.count',
    'o2ocart.checkCartInit',
    'order.setElectronInvoice',  //pc 设置电子发票
    'crm.selectCard',
    'crm.getUserRank',
    'crm.sendGift',
    'crm.resetPro',
    'user.privilege',  //pc 会员特权
    'user.collectMobileData', //收集用户手机系统数据
    'crm.selfOmsOrder',
    'crm.cancelOrder',
    'article.getList', // 获取文章列表
    'article.getInfo', // 获取文章详情
    'order.chosePcPayment', //pc  订单变更支付方式
    'crm.orderComplaints', //crm
    'crm.crmsyc',
    'crm.receiveComplaints',
    'order.complaintsList',  //App
    'order.complaintsDetail',
    'order.complaintsFeedback',
    'user.userTradeInfo',   //pc  用户充值订单详细查询
    'order.complaintsList',   //App
    'weixin.user-bind',
    'weixin.menu-getMenu',
    'weixin.menu-setMenu',
    'weixin.pushMessage',
    'weixin.delToken',
    'weixin.getToken',
    'user.userInfoAes',   //pc oms
    'weixin.pushTemplateMessage',
    'weixin.user-isBind',
    'user.mobileLogin', //手机短信直接登录，

    'group.master',
    'group.master_newyear',
    'group.master_newyear_test',
    'group.master_newyearmilk',
    'group.groupList',
    'group.beforeOrder_v1',
    'group.productInfo_v1',
    'group.createOrder_v1',
    'group.getGroupInfo_v1',
    'group.setMemberInfo',
    'user.mobileLogin', //手机短信直接登录
    'weixin.user-getList',
    'weixin.user-getCountryList',
    'weixin.user-getProvinceList',
    'weixin.user-getCityList',
    'weixin.user-countUser',
    'weixin.user-createGroup',
    'weixin.user-joinGroup',
    'weixin.user-delGroup',
    'weixin.user-getGroupList',
    'cms.getCms',   //web cms
    'survey.commit',   //物流问卷
    'vip.recommend',//vip 推荐商品
    'vip.getSaleProduct',//获取会员中心特惠商品
    'vip.getBonusPoint',//获取积分兑换配置
    'weixin.menu-delConditional',
    'weixin.menu-addConditional',
    'weixin.user-getWeixinUserInfo',
    'weixin.user-updateWeixinUserInfo',
    'presell.orderInit',   //预售订单
    'presell.createOrder',  //预售订单
    'weixin.material-getCount',
    'weixin.material-syncImage',
    'weixin.material-syncNews',
    'point.getlist',  //积分兑换商品
    'mobile.score'  //蚁盾风控
);
